import React, {Fragment} from 'react';
import type {NextPage} from 'next';
import Head from 'next/head';

const LandingPage: NextPage = () => (
  <Fragment>
    <Head>
      <title>reLink - Link Shortner</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
  </Fragment>
);

export default LandingPage;
